version: '3.7'

services:
  terraform:
    image: hashicorp/terraform:0.12.23
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TF_VAR_db_username=${PGUSER}
      - TF_VAR_db_password=${PGPASSWORD}
      - TF_VAR_jwt_secret=${JWT_SECRET}